### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by nikolovay** [chef-cats/raster-cli#13]
Because we will use C++, I think we need a memory leak detector. I found one for visual studio(https://marketplace.visualstudio.com/items?itemName=ArkadyShapkin.VisualLeakDetectorforVisualC). It works for VS 2019, also. Do you want to use it?

**Comment by ivancho-ifa** [comment]
Sure! Can you research some more on how to use it? Do we include `<vld.h>` just in the application starting point or we need it in every file?

**Comment by nikolovay** [comment]
First, you have to download the exe from here: https://github.com/KindDragon/vld/releases/download/v2.5.1/vld-2.5.1-setup.exe. After that, you have to add #include <vld.h> into the project. I added it only into the main file and it worked. 
Note: tested on another project with more than one file.
From vld documentation: "In at least one C/C++ source file from your program, include the vld.h header file. It should not matter which file you add the include statement to. "
